export const filterOptions = [
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Burger",
  "Pizza",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "Appeteasers",
  "Bakery",
  "BBQ & Grill",
  "Beef",
  "Bengali Items",
  "last item",
];